runtime: php
env: flex

runtime_config: 
  document_root: .

# Ensure we skip ".env", which is only for local development
skip_files: 
    - .env

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 100

env_variables:
    # Put production environment variables here.
    APP_DEBUG: true
    APP_ENV: production
    APP_KEY: base64:WLmFdcszUOyepOUL4dtwNviAAYA3NLNNEaIo/rEXXaQ=
    APP_NAME: "GCP App - CODE"

    DB_CONNECTION: mysql
    DB_HOST: 34.101.152.159
    DB_PORT: 3306
    DB_DATABASE: root
    DB_USERNAME: root
    DB_PASSWORD: plantcycopedianew

    LOG_LEVEL: debug
